{% set name = "napari-nifti" %}
{% set version = "0.0.15" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 446479cb6ebbe03ad33a7b4270227ceb9ca273bf285ba0b8bf304c19df3a40c9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - numpy
    - python >=3.8
    - simpleitk

test:
  imports:
    - napari_nifti
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/MIC-DKFZ/napari-nifti
  summary: |
    A napari plugin for reading and writing NIFTI files that have
    the extension .nii or .nii.gz.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
    - Karol-G
