{% set name = "napari-nifti" %}
{% set version = "0.0.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari-nifti-{{ version }}.tar.gz
  sha256: 86d05ad82d541045273a356df29ca8a256a862ea0351b6647b92db47a5764f3d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - numpy
    - python >=3.8
    - simpleitk

test:
  imports:
    - napari_nifti
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/MIC-DKFZ/napari-nifti
  summary: |
    A napari plugin for reading and writing NIFTI files that have
    the extension .nii or .nii.gz.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
    - Karol-G
